# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: awscpe
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: '3'


# Here we set the provider to AWS and also set the IAM role to enable
# putting objects into a bucket (required in order to add website files)
# and also allow reading of the DynamoDB table.
provider:
  name: aws
  runtime: python3.9
  region: ap-southeast-2
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "dynamodb:GetItem"
            - "dynamodb:Query"
            - "dynamodb:Scan"
            - "s3:PutObject" 
          Resource:
            - "arn:aws:dynamodb:ap-southeast-2:637423330642:table/awsquiz"
            - "arn:aws:dynamodb:ap-southeast-2:637423330642:table/awsquiz/index/*"
        - Effect: "Allow"
          Action:
            - "s3:PutBucketPolicy"
          Resource: "arn:aws:s3:::t04awscpe"   

# Here we set lambda function that will read from the DynamoDB table
# and also create the API Gateway.          
functions:
  awscpe_fetch_questions:
    handler: handler.awscpe_fetch_questions
    events:
      - http:
          path: fetch-questions
          method: get
          cors: true

# This required into order to copy files into the static website bucket.
plugins:
  - serverless-s3-sync

# Configuration to copy files into the static website bucket.
custom:
  s3Sync:
    - bucketName: t04awscpe
      localDir: staticwebsite

# Here we create the bucket for the static website and configure it as a static website.
resources:
  Resources:
    WebsiteBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: t04awscpe
        WebsiteConfiguration:
          IndexDocument: index.html
          ErrorDocument: error.html







