org: kdaviesnz
app: mac-py-st
service: mac-py-st

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.10
  region: ap-southeast-2
  environment:
    S3_BUCKET_NAME: 'kdaviesnz-photos'

  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:GetObject
      Resource:
        - 'arn:aws:s3:::${self:provider.environment.S3_BUCKET_NAME}/uploads/*'
    - Effect: Allow
      Action:
        - s3:PutObject
      Resource:
        - 'arn:aws:s3:::${self:provider.environment.S3_BUCKET_NAME}/thumbnails/*'      

functions:
  create_thumbnail_function:
    handler: handler.create_thumbnail
    name: create-thumbnail-function
    events:
      - s3:
          bucket: '${self:provider.environment.S3_BUCKET_NAME}'
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploads/
            - suffix: .jpg

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: false
