# Requires:
# npm install serverless-s3-sync

service: awsquiz

app: awsquiz
org: kdaviesnz

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9
  region: ap-southeast-2
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "dynamodb:GetItem"
            - "dynamodb:Query"
            - "dynamodb:Scan"
            - "s3:PutObject" 
          Resource:
            - "arn:aws:dynamodb:ap-southeast-2:637423330642:table/awsquiz"
            - "arn:aws:dynamodb:ap-southeast-2:637423330642:table/awsquiz/index/*"
        - Effect: "Allow"
          Action:
            - "s3:PutBucketPolicy"
          Resource: "arn:aws:s3:::t01awsquizawesomesite"   
          
functions:
  awsquiz_fetch_questions:
    handler: handler.awsquiz_fetch_questions
    events:
      - http:
          path: fetch-questions
          method: get
          cors: true


plugins:
  - serverless-s3-sync

custom:
  s3Sync:
    - bucketName: t01awsquizawesomesite
      localDir: staticwebsite

resources:
  Resources:
    WebsiteBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: t01awsquizawesomesite
        WebsiteConfiguration:
          IndexDocument: index.html
          ErrorDocument: error.html
